packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  next: 15.5.9
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react19:
    react: 19.1.4
    react-dom: 19.1.4
    "@types/react": 19.1.4
    "@types/react-dom": 19.1.4
  payload:
    "@payloadcms/db-postgres": 3.72.0
    "@payloadcms/richtext-lexical": 3.72.0
    "@payloadcms/next": 3.72.0
    "@payloadcms/storage-vercel-blob": 3.72.0
    "@payloadcms/ui": 3.72.0
    payload: 3.72.0
