packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react19:
    react: 19.0.0-rc-69d4b800-20241021
    react-dom: 19.0.0-rc-69d4b800-20241021
    "@types/react": npm:types-react@19.0.0-rc.1
    "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
