import { randomUUID } from "node:crypto";
import { mask, vercelProjectId, vercelTeamId } from "./deployment-tools";

export async function vercelApi<T>(path: string, method = "GET", body?: unknown): Promise<T> {
  const token = process.env.VERCEL_TOKEN;
  if (!token) throw new Error("Missing VERCEL_TOKEN");
  const url = new URL(path, "https://api.vercel.com");
  url.searchParams.set("teamId", vercelTeamId);
  const response = await fetch(url, {
    method,
    headers: { authorization: `Bearer ${token}`, "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok)
    throw new Error(`Vercel ${method} ${url.pathname} failed with HTTP ${response.status}`);
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}

export async function setDatabaseEnvironment(
  url: string,
  target: "production" | "preview",
  branch?: string,
) {
  if (target === "preview" && !branch) throw new Error("Preview environment requires a branch");
  await vercelApi(`/v10/projects/${vercelProjectId}/env?upsert=true`, "POST", {
    key: "SUSHIRO_DATABASE_URL",
    value: url,
    type: "encrypted",
    target: [target],
    ...(branch ? { gitBranch: branch } : {}),
  });
}

export async function removePreviewEnvironment(branch: string) {
  if (!branch || branch === "main") throw new Error("A preview branch is required");
  const { envs } = await vercelApi<{
    envs: { id: string; key: string; gitBranch?: string; target: string[] }[];
  }>(`/v10/projects/${vercelProjectId}/env`);
  for (const variable of envs) {
    if (
      variable.key === "SUSHIRO_DATABASE_URL" &&
      variable.gitBranch === branch &&
      variable.target.includes("preview")
    ) {
      await vercelApi(`/v9/projects/${vercelProjectId}/env/${variable.id}`, "DELETE");
    }
  }
}

export async function checkDeploymentHealth(deploymentUrl: string) {
  const path = `/v1/projects/${vercelProjectId}/protection-bypass`;
  const note = `Sushiro CI health check ${randomUUID()}`;
  const result = await vercelApi<{
    protectionBypass: Record<string, { note?: string; scope: string }>;
  }>(path, "PATCH", { generate: { note } });
  const secret = Object.entries(result.protectionBypass).find(
    ([, bypass]) => bypass.note === note && bypass.scope === "automation-bypass",
  )?.[0];
  if (!secret) throw new Error("Vercel did not create the health-check bypass");
  mask(secret);
  try {
    const signal = AbortSignal.timeout(30_000);
    for (let attempt = 0; attempt < 10; attempt += 1) {
      const response = await fetch(new URL("/api/health", deploymentUrl), {
        headers: { "x-vercel-protection-bypass": secret },
        redirect: "manual",
        signal,
      });
      const location = new URL(response.headers.get("location") ?? "/", deploymentUrl);
      // Newly generated bypasses take a few seconds to reach Vercel's edge.
      // Retry the auth redirect locally; never forward the secret to its target.
      if (
        response.status === 302 &&
        location.origin === "https://vercel.com" &&
        location.pathname === "/sso-api"
      ) {
        await response.body?.cancel();
        await new Promise((resolve) => setTimeout(resolve, 2_000));
        continue;
      }
      if (!response.ok || (await response.json()).ok !== true) {
        throw new Error("The candidate deployment failed its database health check");
      }
      return;
    }
    throw new Error("Vercel's health-check bypass did not become active");
  } finally {
    await vercelApi(path, "PATCH", { revoke: { secret, regenerate: false } });
  }
}
