export const planCopy = {
  en: {
    addBranch: "Add branch",
    allNote: "At {time} on a {day}, shortest wait first. Star a branch to compare it above.",
    allTerritories: "All",
    called: "Called about {from} to {to}",
    calledAt: "Called about {from}",
    dragNote: "Drag the time, or step 5 minutes",
    earlier: "5 minutes earlier",
    emptyMine: "Star the branches you are choosing between to compare them here.",
    footnote:
      "Usual ranges come from the same weekday over the last eight weeks and cover eight waits in ten. Public holidays count as Sundays. The dot colour is the queue band at the chosen time.",
    intro:
      "Pick a day and the time you would take a ticket. Each branch shows how long people usually waited from then until their number was called.",
    keyToday: "Today so far",
    keyUsual: "Usual range on {day}s",
    later: "5 minutes later",
    mineNote: "If you take a ticket at {time} on a {day}. Shortest wait first.",
    noQueue: "No queue",
    noShorter: "No shorter time within an hour",
    noUsual: "No usual wait recorded for this time",
    noWait: "Usually no wait",
    now: "Now {wait} min",
    range: "{low} to {high}",
    shorterNearby: "Shorter nearby",
    shortest: "Shortest",
    showAll: "Show all {count} branches",
    showFewer: "Show fewer",
    stepNote: "{day} · steps of 5 minutes",
    takeTicketAt: "Take a ticket at",
    ticketTime: "Ticket time",
    tip: "{time} · {range} min",
    tipNoQueue: "{time} · no queue",
    title: "Plan a meal",
    todayChip: "Today · {day}",
    waitUnit: "min wait",
  },
  "zh-HK": {
    addBranch: "加入分店",
    allNote: "{day} {time} 攞籌，由最短輪候排起。加星就可以喺上面比較。",
    allTerritories: "全部",
    called: "約 {from} 至 {to} 叫號",
    calledAt: "約 {from} 叫號",
    dragNote: "拖動時間，或者每次調 5 分鐘",
    earlier: "早 5 分鐘",
    emptyMine: "幫你考慮緊嘅分店加星，就可以喺度比較。",
    footnote:
      "平時範圍嚟自過去八個星期同一個星期幾嘅紀錄，包到十次入面八次嘅輪候時間。公眾假期當星期日計。圓點顏色係所揀時間嘅輪候級別。",
    intro: "揀邊日同幾點攞籌，就睇到每間分店通常要等幾耐先叫到號。",
    keyToday: "今日至今",
    keyUsual: "平時範圍",
    later: "遲 5 分鐘",
    mineNote: "{day} {time} 攞籌，由最短輪候排起",
    noQueue: "暫無輪候",
    noShorter: "一個鐘內冇更短嘅時間",
    noUsual: "呢個時間未有平時紀錄",
    noWait: "通常唔使等",
    now: "而家 {wait} 分鐘",
    range: "{low} 至 {high}",
    shorterNearby: "附近較短",
    shortest: "最短",
    showAll: "顯示全部 {count} 間",
    showFewer: "顯示較少",
    stepNote: "{day} · 每次調 5 分鐘",
    takeTicketAt: "幾點攞籌？",
    ticketTime: "攞籌時間",
    tip: "{time} 會短啲 · {range} 分鐘",
    tipNoQueue: "{time} 會短啲 · 暫無輪候",
    title: "計劃用餐",
    todayChip: "今日",
    waitUnit: "分鐘",
  },
} as const;
