export const planCopy = {
  en: {
    addBranch: "Add branch",
    allNote: "At {time} on a {day}, shortest wait first. Star a branch to compare it above.",
    allNoteEat:
      "To eat at {time} on a {day}, shortest wait first. Star a branch to compare it above.",
    allTerritories: "All",
    called: "Called about {from} to {to}",
    calledAt: "Called about {from}",
    dragNote: "Drag the time, or step 5 minutes",
    dragNoteEat: "Drag the eating time, or step 5 minutes",
    earlier: "5 minutes earlier",
    eatCalled: "Usually called {from} to {to}",
    eatCalledAt: "Usually called about {from}",
    eatEarly: "Tickets here are not usually called by {time}",
    eatLate: "Usually called {from} to {to}, after {time}",
    eatLateAt: "Usually called about {from}, after {time}",
    eatNow: "Take a ticket now",
    eatQuestion: "What time to eat?",
    eatTicketAfter: "",
    eatTicketBefore: "Take a ticket about",
    eatTime: "Eating time",
    eatWaitThen: "Usual wait then",
    emptyMine: "Star the branches you are choosing between to compare them here.",
    footnoteEat:
      "The dot is when to take the ticket, the dashed line is the usual wait, and the upright line is when you want to eat. Each ticket time is the latest one that is usually called by then.",
    footnote:
      "The usual range is where the wait sat on the middle half of days, from the same weekday over the last eight weeks. The lighter band reaches the quiet and busy days. Public holidays count as Sundays. The dot colour is the queue band at the chosen time.",
    intro:
      "Pick a day, then the time you would take a ticket or the time you want to eat. Each branch answers from how long people usually waited.",
    keyToday: "Today so far",
    keyUsual: "Usual range on {day}s",
    keyWide: "Quiet and busy days",
    later: "5 minutes later",
    mineNote: "If you take a ticket at {time} on a {day}. Shortest wait first.",
    mineNoteEat: "To eat at {time} on a {day}. Shortest wait first.",
    modeEat: "I want to eat at",
    modeLabel: "Plan by",
    modeTicket: "Take a ticket at",
    noneInTime: "No branch usually calls a ticket by {time}",
    noQueue: "No queue",
    noShorter: "No shorter time within an hour",
    noUsual: "No usual wait recorded for this time",
    noWait: "Usually no wait",
    now: "Now {wait} min",
    range: "{low} to {high}",
    rowNoQueueThen: "No queue then",
    rowTicketAfter: "",
    rowTicketBefore: "Ticket about",
    rowWaitThen: "{range} min wait then",
    shorterNearby: "Shorter nearby",
    shortest: "Shortest",
    showAll: "Show all {count} branches",
    showFewer: "Show fewer",
    stepNote: "{day} · steps of 5 minutes",
    ticketQuestion: "What time for a ticket?",
    ticketTime: "Ticket time",
    tip: "{time} · {range} min",
    tipNoQueue: "{time} · no queue",
    title: "Plan a meal",
    todayChip: "Today · {day}",
    waitUnit: "min wait",
  },
  "zh-HK": {
    addBranch: "加入分店",
    allNote: "{day} {time} 攞籌，由最短輪候排起。加星就可以喺上面比較。",
    allNoteEat: "{day}想 {time} 食，由等得最短排起。加星就可以喺上面比較。",
    allTerritories: "全部",
    called: "約 {from} 至 {to} 叫號",
    calledAt: "約 {from} 叫號",
    dragNote: "拖動時間，或者每次調 5 分鐘",
    dragNoteEat: "拖動用餐時間，或者每次調 5 分鐘",
    earlier: "早 5 分鐘",
    eatCalled: "通常 {from} 至 {to} 叫號",
    eatCalledAt: "通常約 {from} 叫號",
    eatEarly: "呢間通常趕唔切 {time} 前叫號",
    eatLate: "通常 {from} 至 {to} 叫號，遲過 {time}",
    eatLateAt: "通常約 {from} 叫號，遲過 {time}",
    eatNow: "而家就要攞籌",
    eatQuestion: "想幾點食？",
    eatTicketAfter: "攞籌",
    eatTicketBefore: "大約",
    eatTime: "用餐時間",
    eatWaitThen: "嗰陣通常要等",
    emptyMine: "幫你考慮緊嘅分店加星，就可以喺度比較。",
    footnoteEat:
      "圓點係幾時攞籌，虛線係平時要等幾耐，直線係你想食嘅時間。攞籌時間係通常趕得切叫號嘅最遲時間。",
    footnote:
      "平時範圍係過去八個星期同一個星期幾入面，中間一半日子嘅輪候時間。淺色範圍包埋特別靜同特別旺嘅日子。公眾假期當星期日計。圓點顏色係所揀時間嘅輪候級別。",
    intro: "揀邊日，再揀幾點攞籌或者幾點想食。每間分店都會按平時嘅輪候答你。",
    keyToday: "今日至今",
    keyUsual: "平時範圍",
    keyWide: "特別靜或者特別旺嘅日子",
    later: "遲 5 分鐘",
    mineNote: "{day} {time} 攞籌，由最短輪候排起",
    mineNoteEat: "{day}想 {time} 食，由等得最短排起",
    modeEat: "幾點想食",
    modeLabel: "計劃方式",
    modeTicket: "幾點攞籌",
    noneInTime: "通常冇分店趕得切 {time} 前叫號",
    noQueue: "暫無輪候",
    noShorter: "一個鐘內冇更短嘅時間",
    noUsual: "呢個時間未有平時紀錄",
    noWait: "通常唔使等",
    now: "而家 {wait} 分鐘",
    range: "{low} 至 {high}",
    rowNoQueueThen: "嗰陣唔使等",
    rowTicketAfter: "攞籌",
    rowTicketBefore: "",
    rowWaitThen: "嗰陣要等 {range} 分鐘",
    shorterNearby: "附近較短",
    shortest: "最短",
    showAll: "顯示全部 {count} 間",
    showFewer: "顯示較少",
    stepNote: "{day} · 每次調 5 分鐘",
    ticketQuestion: "幾點攞籌？",
    ticketTime: "攞籌時間",
    tip: "{time} 會短啲 · {range} 分鐘",
    tipNoQueue: "{time} 會短啲 · 暫無輪候",
    title: "計劃用餐",
    todayChip: "今日",
    waitUnit: "分鐘",
  },
} as const;
