export const statsCopy = {
  en: {
    averageAcross: "Average wait {wait} min across all branches",
    branchesNote: "Sorted by longest wait.",
    branchesTitle: "Branches on this day",
    busiestSlot: "Busiest time of the week",
    busiestTime: "Busiest time",
    calmestDay: "Calmest day",
    chartNote: "{count} branches · Sushiro's estimate in minutes · while tickets are issued",
    chartTitle: "Average wait across Hong Kong",
    columnAverage: "Average wait",
    columnBranch: "Branch",
    columnDay: "Through the day",
    columnLongest: "Longest wait",
    columnOver30: "Time over 30 min",
    compareNote: "Average wait at weekend dinner, Saturday and Sunday from 18:00.",
    compareTitle: "Branches compared",
    daily: "Daily history",
    date: "Date",
    dayAverage: "Average wait {wait} min while tickets are issued",
    heatNote:
      "All branches, {from} to {to}. Each cell is a two-hour slot, in minutes, counted only while tickets were being issued.",
    heatTitle: "Average wait by weekday and time",
    hours: "h",
    intro: "What the queues actually did, from recorded queue data.",
    longestAt: "{store} at {time}",
    longestWait: "Longest wait",
    minAverage: "min average",
    nextDay: "Next day",
    noData: "No recorded data for this day.",
    noPatterns: "Patterns will appear once a week of data is recorded.",
    ofBranches: "of {count}",
    overAnHour: "Branches over an hour",
    patterns: "Patterns",
    peakAt: "at {time}",
    previousDay: "Previous day",
    quietestBranch: "Quietest branch",
    quietestSlot: "Quietest afternoon or evening",
    reachedHour: "Reached a 60 min wait at some point",
    showAll: "Show all {count} branches",
    showFewer: "Show fewer",
    slot: "{day} {from}:00 to {to}:00",
    title: "Stats",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  },
  "zh-HK": {
    averageAcross: "全部分店平均輪候 {wait} 分鐘",
    branchesNote: "按最長輪候排序。",
    branchesTitle: "當日各分店",
    busiestSlot: "一星期最繁忙時段",
    busiestTime: "最繁忙時間",
    calmestDay: "最靜嘅一日",
    chartNote: "{count} 間分店 · 壽司郎估計輪候分鐘 · 只計派籌期間",
    chartTitle: "全港平均輪候",
    columnAverage: "平均輪候",
    columnBranch: "分店",
    columnDay: "全日走勢",
    columnLongest: "最長輪候",
    columnOver30: "超過 30 分鐘",
    compareNote: "星期六、日 18:00 起嘅平均輪候。",
    compareTitle: "分店比較",
    daily: "每日紀錄",
    date: "日期",
    dayAverage: "派籌期間平均輪候 {wait} 分鐘",
    heatNote: "全部分店，{from} 至 {to}。每格代表兩小時，單位係分鐘，只計派籌期間。",
    heatTitle: "按星期同時段嘅平均輪候",
    hours: "小時",
    intro: "睇返壽司郎分店實際輪候紀錄。",
    longestAt: "{store}，{time}",
    longestWait: "最長輪候",
    minAverage: "分鐘（平均）",
    nextDay: "後一日",
    noData: "呢日未有紀錄。",
    noPatterns: "記錄滿一星期之後會顯示規律。",
    ofBranches: "共 {count} 間",
    overAnHour: "輪候超過一小時嘅分店",
    patterns: "規律",
    peakAt: "{time}",
    previousDay: "前一日",
    quietestBranch: "最靜分店",
    quietestSlot: "下午至晚上最靜時段",
    reachedHour: "曾經輪候 60 分鐘或以上",
    showAll: "顯示全部 {count} 間",
    showFewer: "顯示較少",
    slot: "{day} {from}:00 至 {to}:00",
    title: "統計",
    weekdays: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
  },
} as const;
