export const statsCopy = {
  en: {
    againstRank: "{branch} ranks {rank} of {count}, longest first.",
    againstTitle: "Against other branches",
    averageAcross: "Average wait {wait} min across all branches",
    averageShort: "Average",
    branchHeat: "{branch} by weekday and half hour",
    branchHeatNote:
      "{from} to {to}, in minutes, counted only while tickets were being issued. Public holidays count as Sundays.",
    branchesNote: "Sorted by longest wait. Select a branch to see its day.",
    branchesTitle: "Branches on this day",
    busiestSlot: "Busiest half hour of the week",
    busiestTime: "Busiest time",
    calmestDay: "Calmest day",
    chartNote: "{count} branches · Sushiro's estimate in minutes · while tickets are issued",
    chartTitle: "Average wait across Hong Kong",
    clearBranch: "show all branches",
    columnAverage: "Average wait",
    columnBranch: "Branch",
    columnDate: "Day",
    columnDay: "Through the day",
    columnLongest: "Longest wait",
    columnOver30: "Time over 30 min",
    compareNote: "Average wait at weekend dinner, Saturday and Sunday from 18:00.",
    compareTitle: "Branches compared",
    daily: "Daily history",
    date: "Date",
    dayAverage: "Average wait {wait} min while tickets are issued",
    heatNote:
      "All branches, {from} to {to}, in minutes, counted only while tickets were being issued. Public holidays count as Sundays.",
    heatTitle: "Average wait by weekday and half hour",
    levelsNote: "60 and over, then 120 and over, are darker",
    never: "Never",
    hours: "h",
    intro: "What the queues actually did, from recorded queue data.",
    keyRange: "Range on other {weekday}s",
    keyThisDay: "This day",
    longestAt: "{store} at {time}",
    longestWait: "Longest wait",
    minAverage: "min average",
    neverOver30: "Never over 30 min",
    nextDay: "Next day",
    noData: "No recorded data for this day.",
    noPatterns: "Patterns will appear once a week of data is recorded.",
    noUsual: "No other {weekday} recorded yet",
    ofBranches: "of {count}",
    overAnHour: "Branches over an hour",
    overAnHourColumn: "Over an hour",
    overWindow: "From {from} to {to}",
    patterns: "Patterns",
    peakAt: "at {time}",
    peakHigher: "This {weekday} peaked higher than usual",
    peakLower: "This {weekday} peaked lower than usual",
    peakWithin: "This {weekday} was within the usual range",
    previousDay: "Previous day",
    quietestBranch: "Quietest branch",
    quietestSlot: "Quietest half hour after noon",
    rangeJoin: "{low} to {high}",
    recordsFrom: "Records start {date}",
    reachedHour: "Reached a 60 min wait at some point",
    recentDays: "Recent days at {branch}",
    selectDay: "Select a day to see it above.",
    showAll: "Show all {count} branches",
    showAllDays: "Show all {count} days",
    showFewer: "Show fewer",
    shownAbove: "Shown above",
    slot: "{day} {from} to {to}",
    throughDay: "{branch} through the day",
    title: "Stats",
    today: "Today",
    usualPeak: "Usual {weekday} peak",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    weekdaysLong: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    weekdaysNarrow: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    weekdaysShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    whileIssued: "While tickets were issued",
  },
  "zh-HK": {
    againstRank: "{branch}排第 {rank}，共 {count} 間，由最長排起。",
    againstTitle: "同其他分店比較",
    averageAcross: "全部分店平均輪候 {wait} 分鐘",
    averageShort: "平均",
    branchHeat: "{branch}：按星期同半個鐘",
    branchHeatNote: "{from} 至 {to}，單位係分鐘，只計派籌期間。公眾假期當星期日計。",
    branchesNote: "按最長輪候排序。揀一間分店睇佢當日情況。",
    branchesTitle: "當日各分店",
    busiestSlot: "一星期最繁忙半個鐘",
    busiestTime: "最繁忙時間",
    calmestDay: "最靜嘅一日",
    chartNote: "{count} 間分店 · 壽司郎估計輪候分鐘 · 只計派籌期間",
    chartTitle: "全港平均輪候",
    clearBranch: "顯示全部分店",
    columnAverage: "平均輪候",
    columnBranch: "分店",
    columnDate: "日期",
    columnDay: "全日走勢",
    columnLongest: "最長輪候",
    columnOver30: "超過 30 分鐘",
    compareNote: "星期六、日 18:00 起嘅平均輪候。",
    compareTitle: "分店比較",
    daily: "每日紀錄",
    date: "日期",
    dayAverage: "派籌期間平均輪候 {wait} 分鐘",
    heatNote: "全部分店，{from} 至 {to}，單位係分鐘，只計派籌期間。公眾假期當星期日計。",
    heatTitle: "按星期同半個鐘嘅平均輪候",
    levelsNote: "一小時以上同兩小時以上會深色啲",
    never: "冇",
    hours: "小時",
    intro: "睇返壽司郎分店實際輪候紀錄。",
    keyRange: "其他{weekday}嘅範圍",
    keyThisDay: "當日",
    longestAt: "{store}，{time}",
    longestWait: "最長輪候",
    minAverage: "分鐘（平均）",
    neverOver30: "全日未超過 30 分鐘",
    nextDay: "後一日",
    noData: "呢日未有紀錄。",
    noPatterns: "記錄滿一星期之後會顯示規律。",
    noUsual: "未有其他{weekday}嘅紀錄",
    ofBranches: "共 {count} 間",
    overAnHour: "輪候超過一小時嘅分店",
    overAnHourColumn: "超過一小時",
    overWindow: "{from} 至 {to}",
    patterns: "規律",
    peakAt: "{time}",
    peakHigher: "今個{weekday}高峰比平時高",
    peakLower: "今個{weekday}高峰比平時低",
    peakWithin: "今個{weekday}喺平時範圍之內",
    previousDay: "前一日",
    quietestBranch: "最靜分店",
    quietestSlot: "正午後最靜半個鐘",
    rangeJoin: "{low} 至 {high}",
    recordsFrom: "紀錄由 {date} 開始",
    reachedHour: "曾經輪候 60 分鐘或以上",
    recentDays: "{branch}最近幾日",
    selectDay: "揀一日喺上面睇。",
    showAll: "顯示全部 {count} 間",
    showAllDays: "顯示全部 {count} 日",
    showFewer: "顯示較少",
    shownAbove: "上面顯示緊",
    slot: "{day} {from} 至 {to}",
    throughDay: "{branch}全日走勢",
    title: "統計",
    today: "今日",
    usualPeak: "平時{weekday}高峰",
    weekdays: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
    weekdaysLong: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
    weekdaysNarrow: ["一", "二", "三", "四", "五", "六", "日"],
    weekdaysShort: ["週一", "週二", "週三", "週四", "週五", "週六", "週日"],
    whileIssued: "只計派籌期間",
  },
} as const;
