export const ticketCopy = {
  en: {
    title: "Share your wait",
    intro: "Share your ticket to help improve wait estimates.",
    newTicket: "Add a ticket",
    branch: "Branch",
    chooseBranch: "Choose your branch",
    number: "Ticket number",
    example: "e.g. 123 or 123-1",
    taken: "When did you take it?",
    now: "Just now",
    earlier: "Earlier",
    takenAt: "Ticket taken at",
    save: "Save ticket",
    saving: "Saving…",
    reports: "Your tickets",
    waiting: "Waiting",
    seen: "Seen in feed",
    confirmed: "Call time saved",
    left: "Left the queue",
    expired: "Tracking ended",
    elapsed: "Elapsed",
    waited: "Time until called",
    minutes: "min",
    feed: "Currently called",
    noCalls: "No called numbers supplied",
    feedUnavailable: "Live numbers are unavailable. You can still report your call time.",
    sighting: "First seen in feed",
    sightingNote:
      "A feed sighting may be later than the actual call. You can record the time you heard it.",
    called: "My ticket was called",
    editCall: "Edit call time",
    calledAt: "Actual call time",
    confirm: "Save call time",
    cancel: "Cancel",
    leave: "I left the queue",
    thanks: "Thanks. Your reported call time helps check our estimates.",
    loadError: "Unable to load your tickets. Try refreshing.",
    saveError: "Unable to save. Your details are still here. Please try again.",
    store: "Choose a branch from the list.",
    ticket: "Enter the full ticket number, such as 123 or 123-1.",
    takenTime: "Choose a time within the past 24 hours.",
    calledTime:
      "Choose a time after taking the ticket, within the following 24 hours and not in the future.",
    added: "Ticket saved.",
    retry: "Try again",
    timeZone: "Hong Kong time",
    loading: "Loading tickets…",
    link: "Track my ticket",
  },
  "zh-HK": {
    title: "記低輪候時間",
    intro: "記低籌號，幫手改善輪候估算。",
    newTicket: "加入籌號",
    branch: "分店",
    chooseBranch: "選擇你的分店",
    number: "籌號",
    example: "例如 123 或 123-1",
    taken: "幾時攞籌？",
    now: "啱啱攞",
    earlier: "之前攞",
    takenAt: "攞籌時間",
    save: "儲存籌號",
    saving: "儲存中…",
    reports: "你的籌號",
    waiting: "輪候中",
    seen: "已喺叫號資料出現",
    confirmed: "已記錄叫號時間",
    left: "已離開隊伍",
    expired: "追蹤已結束",
    elapsed: "已過時間",
    waited: "輪候至叫號",
    minutes: "分鐘",
    feed: "目前叫號",
    noCalls: "暫無叫號資料",
    feedUnavailable: "暫時未能取得即時籌號。你仍然可以記錄叫號時間。",
    sighting: "首次喺資料見到籌號",
    sightingNote: "資料顯示時間可能遲過實際叫號。你可以填寫自己聽到叫號嘅時間。",
    called: "叫到我個籌號",
    editCall: "更改叫號時間",
    calledAt: "實際叫號時間",
    confirm: "儲存叫號時間",
    cancel: "取消",
    leave: "我已經離開隊伍",
    thanks: "多謝！你提供嘅叫號時間會用嚟核對輪候估算。",
    loadError: "未能載入你的籌號，請再試更新。",
    saveError: "未能儲存，你填寫嘅資料仲喺度，請再試一次。",
    store: "請喺清單選擇分店。",
    ticket: "請輸入完整籌號，例如 123 或 123-1。",
    takenTime: "請選擇過去 24 小時內嘅攞籌時間。",
    calledTime: "請選擇攞籌之後 24 小時內嘅叫號時間，時間唔可以係未來。",
    added: "已儲存籌號。",
    retry: "重試",
    timeZone: "香港時間",
    loading: "載入籌號中…",
    link: "追蹤我的籌號",
  },
} as const;
